config/routes.rb
Fantadea::Application.routes.draw do
  
  resources :ideas_admin

  resources :ideas   
  resources :site_suggestions

  match 'ideas/create_point' => 'ideas#create_point', :as => :create_point
  
  match 'ideas_admin/edit/:id' => 'ideas_admin#edit', :as => :edit_ideas_admin
  match 'ideas_admin/destroy/:id' => 'ideas_admin#destroy', :as => :destroy_ideas_admin
  match 'ideas_admin/' => 'ideas#index', :as => :ideas_admin

  

   root :to => 'home#index'

end

app/models/bad_point.rb
class BadPoint < ActiveRecord::Base
  belongs_to :idea
end

app/models/consideration_point.rb
class ConsiderationPoint < ActiveRecord::Base
  belongs_to :idea
end

app/models/good_point.rb
class GoodPoint < ActiveRecord::Base
  belongs_to :idea
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  has_many :good_points, :order => 'created_at DESC', :dependent => :delete_all
  has_many :bad_points, :order => 'created_at DESC', :dependent => :delete_all
  has_many :consideration_points, :order => 'created_at DESC', :dependent => :delete_all
  
  validates_presence_of :name
  validates_presence_of :description
  
  NAME_LENGTH = 64
  DESCRIPTION_LENGTH = 512
  POINT_LENGTH = 128
  
  def self.search(search)
    if search
      search.strip!
      where('UPPER(name) LIKE UPPER(?)  OR UPPER(description) LIKE UPPER(?)', "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/settings.yml"
  namespace Rails.env
end

app/models/site_suggestion.rb
class SiteSuggestion < ActiveRecord::Base
  TEXT_LENGTH = 256
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ideas = Idea.order("created_at desc").limit(10)
  end  
end

app/controllers/ideas_admin_controller.rb
class IdeasAdminController < ApplicationController
  
  force_ssl
  http_basic_authenticate_with :name => Settings.basic_auth_user, :password => Settings.basic_auth_password
  
  
  # GET /ideas
  # GET /ideas.json
    force_ssl
  def index
    @ideas = Idea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_admin_path }
      format.json { head :no_content }
    end
  end
  
  protected
  
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.search(params[:search]).paginate(:per_page => 10, :page => params[:page])
  end
  
  def show
    @idea = Idea.find(params[:id])
    @good_point = GoodPoint.new
    @bad_point = BadPoint.new
    @consideration_point = ConsiderationPoint.new
    
    if request.xhr?
      respond_to do |format|
          format.html { render :layout => 'empty' }
      end
    end
  end
  
  def create
    @idea = Idea.new(params[:idea])
    @idea.description = @idea.description.gsub(/\n/, '')
    @idea.save  
    flash[:isNew] = "true"
    redirect_to @idea
  end
  
  def create_point
    @point_name = params[:point_name] 
    
    point_class = Kernel.const_get(@point_name.camelize + 'Point')
    @point = point_class.new(params[(@point_name + '_point').to_sym]) 
       
    assign_idea_to_point @point 
    if @point.save
      # render :nothing => true
      respond_to do |format|
          format.json {  render json: @point, status: :created }
      end
    else
      respond_to do |format|
          format.json {  render json: @point.errors, status: :unprocessable_entity }
      end
    end    

  end
  


  private
  
  def assign_idea_to_point point
    @idea = Idea.find(params[:id])  
    point.idea = @idea
  end  


  
end

app/controllers/site_suggestions_controller.rb
class SiteSuggestionsController < ApplicationController
  def create
    @site_suggestion = SiteSuggestion.new(params[:site_suggestion])
    @site_suggestion.save
    
    render :nothing => true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/site_suggestions_helper.rb
module SiteSuggestionsHelper
end

app/views/good_points/_new.html.erb
<%= form_for @good_point, :remote => true, :url => { :action => "create_good_point"} do |g| %>
	<div class="validation-container clearfix">
		<%= g.text_field :text %>
		<%= g.submit "Add", :class => "btn primary"%>
		<%= hidden_field_tag 'id', @idea.id  %>
	</div>
<% end %>

app/views/home/index.html.erb
<div class="row">	
	<div class="span4">
		<h2 class="vertical-margins">About</h2>
		<div class="about-container">	
			<h4 class="vertical-margins">What is this site?</h4>	
			Do you have an idea and need some quick feedback? Post it on <%= Settings.product_name %> and find out what people think!
			<ul class="no-indent-list">
			    <li>Share ideas with friends via Facebook, Twitter, and email.</li>
				<li>Get feedback from the entire <%= Settings.product_name %> community.</li>
			</ul>
	
			<h4 class="vertical-margins">Getting started</h4>
			<p>Go ahead and add an idea by using the form to your right. Once you add an idea, it'll be posted on the website and look like <a href="#idea-example-modal" data-toggle="modal" >this</a>.</p>
			<%= render :partial => new_site_suggestion_path %>
		</div>
	</div>
	<div class="span4">  
		<h2 class="vertical-margins">Add an Idea</h2>
		<div class="idea-container">
			<%= render :partial => new_idea_path %>
		</div>
	</div>
	<div class="span4"> 
		<h2 class="vertical-margins">Latest Ideas</h2>
		<%= render :partial => "ideas/latest_ideas" %>
	</div>
</div>

<div id="idea-example-modal" class="modal hide" >
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Idea Example</h3>
  </div>
  <div class="modal-body">
    <img src="/assets/idea_example.jpg" alt="Image Help">
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>
</div>

app/views/ideas/_ideas.html.erb
<div class="clickable-container">
	<% @ideas.each do |idea| %>
		<a href="/ideas/<%=idea.id%>">
			<div class="idea-container">
				<%= idea.name %>: <%= idea.description %>
			</div>
		</a>
	<% end %>
</div>
<div>
	<%= will_paginate @ideas %>
</div>

app/views/ideas/_latest_ideas.html.erb
<div class="clickable-container">
	<% @ideas.each do |idea| %>
		<a href="/ideas/<%=idea.id%>" class="auto-ajax">
			<div class="idea-container"><%= idea.name %></div>
		</a>
	<% end %>
</div>

app/views/ideas/_new.html.erb
<%= form_for Idea.new, :html => {  :class => "form-stacked" } do |i| %>
	<div class="clearfix control-group">
		<%= i.label :name, "Give your idea a name"%>
		<a id="idea-examples-link"href="#idea-examples-modal" data-toggle="modal" >See examples</a>

		<%= i.text_field :name, :maxlength => Idea::NAME_LENGTH %>
	
	</div>
	<div class="clearfix control-group">
		<%= i.label :description, "Describe your idea" %>
		<%= i.text_area :description, :rows => 10, :maxlength => Idea::DESCRIPTION_LENGTH %>
	</div>

	<%= i.submit "Add", :class => "btn btn-primary" %>

<% end %>


<div id="idea-examples-modal" class="modal hide" data-backdrop="false" >
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Idea Examples</h3>
  </div>
  <div class="modal-body">
<strong>Name:</strong> Austin Sunday Running Group<br /><strong>Description:</strong> Create a running group that meets up at 10 AM at the Town Lake trail every Sunday.<br /></br /><strong>Name: </strong>Mobile Massages<br /><strong>Description:</strong> Massage therapist travels to businesses during the day and offers chair massages.
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>
</div>

app/views/ideas/_new_good_point.html.erb
<%= form_for @good_point, :remote => true, :url => { :action => "create_good_point"} do |g| %>
	<div class="validation-container clearfix">
		<%= g.text_field :text %>
		<%= g.submit "Add", :class => "btn primary"%>
		<%= hidden_field_tag 'id', @idea.id  %>
	</div>
<% end %>

<div id="good_points">
</div>

app/views/ideas/_points.html.erb
<%= form_for instance_variable_get("@" + point_name + "_point"), :remote => true, :url => create_point_path  do |g| %>
	<div class="validation-container input-append">
		<span>
		<%= g.text_field :text, :id => point_name + "-point-textbox", :placeholder => "Add a thought here...", :maxlength => Idea::POINT_LENGTH %>
		<%= hidden_field_tag 'id', @idea.id  %>
		<%= hidden_field_tag 'point_name', point_name  %>
		<%= g.submit "+", :class => "btn" %>
		</span>
	</div>
<% end %>

<div id="<%= point_name %>_points">
	<% @idea.send("#{point_name}_points").each do |point|  %>
		<div class="<%= point_name %>-container"><%= point.text %></div>
	<% end %>
</div>

app/views/ideas/_search.html.erb
<%= form_tag ideas_path, :method => "get", :id => "ideas_search", :class => "form-search" do %>
	<div class="input-append">
		<%= text_field_tag :search, params[:search], :placeholder => "search" %>
		<%= submit_tag "Go", :class => "btn"%>
	</div>
<% end %>

app/views/ideas/index.html.erb
<h2>Ideas</h2>
<div id="ideas">
	<%= render 'ideas' %>
</div>

app/views/ideas/index.js.erb
$("#ideas").html("<%= escape_javascript(render("ideas")) %>");

app/views/ideas/show.html.erb
<%= link_to "<-- Home", root_path, class: "auto-ajax" %>

<%if flash[:isNew] == "true" then %>
	<div class="row">
		<div class="span12">
		   
			<div id="idea-alert" class="alert alert-info">
				<a class="close" data-dismiss="alert">&times;</a>
				You have just created an idea on Pindea! To get feedback, you can do the following.
				<ul>
				    <li>Use the Twitter button to share this link on Twitter.</li>
					<li>Use the Facebook Like button to share this link on your News Feed.</li>
					<li>Use the Facebook Send button to share this link with only selected friends.</li>
					<li>Copy this URL in your address bar and send the URL through email or text message.
				</ul>
				<strong>Note: </strong> For the Facebook buttons, enter a customized message such as "Please give me feedback on my idea." to increase the chances of people visiting your idea.
			</div>
		</div>
	</div>
<% end %>


<div class="row">
	<div class="span12">
		<h2 id="idea-page-heading">My Idea</h2>
		
	
		<div id="learn-about-idea-link-container">
			<a id="learn-about-idea-link" data-toggle="modal" href="#idea-help-modal">Click here to learn about this page.</a>
		</div>
		<div class="idea-container">
			<%= @idea.name %>
			</br>
			<%= @idea.description %>
		</div>

	    <a href="https://twitter.com/share" class="twitter-share-button" data-text="Check out this idea posted on <%= Settings.product_name %>. Please give some helpful feedback.">Tweet</a>
	    
    
     
	<fb:like send="true" width="450" show_faces="false"></fb:like>
	</div>
</div>

<div class="row">
	<div id="good-idea-column" class="span4 idea-column">
		<h3 class="vertical-margins">Good because...</h3>		
		<%= render :partial =>  'points', :locals => { :point_name => "good" } %>		
	</div>
	<div id="bad-idea-column" class="span4 idea-column">
		<h3 class="vertical-margins">Bad because...</h3>
		<%= render :partial =>  'points', :locals => { :point_name => "bad" } %>
	</div>		
	<div id="consideration-idea-column" class="span4 idea-column">
		<h3 class="vertical-margins">Consider...</h3>
		<%= render :partial =>  'points', :locals => { :point_name => "consideration" } %>	
	</div>

</div>

<div id="idea-help-modal" class="modal hide" >
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>&nbsp;</h3>
  </div>
  <div class="modal-body">
    <img src="/assets/idea_help.jpg" alt="Image Help">
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>
</div>

app/views/ideas_admin/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas_admin/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_admin_path %>

app/views/ideas_admin/index.html.erb
<h1>Listing ideas</h1>

<table id="ideas-admin-table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ideas.each do |idea| %>
  <tr>
	<td><%= idea.name %></td>
	<td><%= idea.description %></td>
    <td><%= link_to 'Show', idea %></td>
    <td><!-- <%= link_to 'Edit', edit_ideas_admin_path(idea) %> --></td>
    <td><%= link_to 'Destroy', destroy_ideas_admin_path(idea), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Idea', new_ideas_admin_path %>

app/views/ideas_admin/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_admin_path %>

app/views/ideas_admin/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_ideas_admin_path(@idea) %> |
<%= link_to 'Back', ideas_admin_path %>

app/views/layouts/_document-ready.html.erb
<script type="text/javascript">
	$(document).ready( function() { fantadea.initializeController("<%=controller.controller_name.camelize.chomp('s')%>"); }); 
	
	<% if Rails.env.production? then%>

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-31481932-1']);
		  _gaq.push(['_setSiteSpeedSampleRate', 100]);
		  _gaq.push(['_trackPageview']);

		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();

	<% end %>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
	<head>
		<title><%= Settings.product_name %></title>
		<%= stylesheet_link_tag    "application" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />	
		<meta property="og:site_name" content="<%= Settings.product_name %>" />
		<meta property="og:title" content="<%= Settings.product_name %> - Get feedback on your ideas!" />
		<meta property="og:image" content='<%= "#{request.scheme}://#{request.host_with_port + request.script_name + image_path('light_bulb.png')}" %>' />
		<meta property="og:type" content="article">
		<meta property="og:url" content="<%= request.url %>" />
		<meta property="fb:app_id" content="160913350693857" />
		<meta property="og:description" content="Check out this idea posted on <%= Settings.product_name %>. Please give some helpful feedback." />
		<%= render :partial => "layouts/document-ready" %>
		<!-- The following is to get the sticky footer to work in IE 8 and greater -->
		<!--[if !IE 7]>
			<style type="text/css">
				#layout-body-wrapper {display:table;height:100%}
			</style>
		<![endif]-->
	
	
	</head>
	<body>
		<div id="fb-root"></div>		
		<script>
		  window.fbAsyncInit = function() {
		    FB.init({
		      appId      : '160913350693857', // App ID
		      //channelUrl : '//WWW.YOUR_DOMAIN.COM/channel.html', // Channel File
		      status     : true, // check login status
		      cookie     : true, // enable cookies to allow the server to access the session
		      xfbml      : true  // parse XFBML
		    });

		    // Additional initialization code here
		  };

		  // Load the SDK Asynchronously
		  (function(d){
		     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
		     if (d.getElementById(id)) {return;}
		     js = d.createElement('script'); js.id = id; js.async = true;
		     js.src = "//connect.facebook.net/en_US/all.js";
		     ref.parentNode.insertBefore(js, ref);
		   }(document));
		</script>	
		<div id="layout-body-wrapper">
			<div id="body">
				<div id="header">
					<div class="container">
						<div class="row">
							<div class="span4">  
								<h1>
									<a href="/" class="auto-ajax"><%= Settings.product_name %></a>
								</h1> 
							</div>
							<div class="span8">
								<div id="search-area">
									<%= render :partial => "/ideas/search" %>
								</div>
							</div>
						</div>
					</div>
				</div>
				
				<div id="content" class="container">
						<%= yield %>
				</div>
				<!-- Below needed so FB Send dialog space doesn't get cut off -->
				<br /><br />
			</div>
		</div>
		<div id="footer">Copyright <%= Settings.product_name %>.com</div>		
	</body>
</html>

app/views/layouts/empty.html.erb
<html>
	<head>

	</head>		
	<body>
		<%= render :partial => "layouts/document-ready" %>
		<%= yield %>
	</body>
</html>

app/views/site_suggestions/_new.html.erb
<%= form_for SiteSuggestion.new, :html => { :class => "form-stacked"}, :remote => true do |s| %>
	<div class="clearfix validation-container input-append">		
		<%= s.label :text, "Comments/suggestions for us" %>
		<%= s.text_field :text, :maxlength => SiteSuggestion::TEXT_LENGTH	%>
		<%= submit_tag "+", :class => "btn"%>
	</div>

<% end%>

app/views/site_suggestions/create.js.erb
 $('#site_suggestion_text').val("");
 $('#site_suggestion_text').attr("placeholder", "Thanks for the feedback!")